stages:
  - build
  - test

image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/
    - core/build
    - core/*/build
    - common/build
    - common/*/build
    - domain/*/build
    - game/build
    - admin/build

build_dev:
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew build
    - echo "빌드 완료"
  tags:
    - local

test_dev:
  stage: test
  script:
    - echo "이 Job은 serverWas 프로젝트를 테스트합니다."
    - ./gradlew test
  tags:
    - local