spring:
  profiles:
    group:
      local:
        - "local-core"
        - "local-common"
        - "local-domain-db"
        - "local-domain-redis"
        - "local-game"
      dev:
        - "dev-core"
        - "dev-common"
        - "dev-domain-db"
        - "dev-domain-redis"
        - "dev-game"

    default: local
