spring:
  config:
    activate:
      on-profile: "local-cheat"
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin
        instance:
          metadata:
            user.name: admin
            user.password: admin
          service-url: http://localhost:9180
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true                 # 정적 리소스에 변화가 있을 때 바로 반영한다.
  thymeleaf:
    cache: false                    #thymeleaf에 대한 캐시를 남기지 않는다. cache=false 설정(운영시는 true)
#    check-template-location: true   # templates 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러를 발생시킨다.
#    prefix: classpath:/templates/
#    suffix: .html
  security:
    user:
      name: admin
      password: admin
      roles:
        - ROLE_ADMIN
        - ROLE_MANAGER
        - ROKE_USER

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 9180

# DB
datasource:
  cheat:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://sl-db-011:3306/ZCOMSY?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: red_database
    password: 123qwe
    max-lifetime: 30000 # 30000ms(30초, hikari min) 동안 사용안한 connection 풀에서 제거 - 컴투스기준 5초(wait_timeout) - 이거 높여야함.
    leak-detection-threshold: 5000

logging:
  level:
    root: INFO
    web: INFO
    sql: INFO
    was: DEBUG
    hikari: INFO  # DEBUG 시 풀 내 connecton, close 정보 볼 수 있음.

sentry:
  dsn: https://3f0d7a32b63c4c0f8e12df4baecc4edf@o921467.ingest.sentry.io/5867907
  #exception-resolver-order: 2147483647
  environment: local-cheat
  logging:
    enabled: true
    minimum-event-level: warn
    minimum-breadcrumb-level: warn



#CUSTOM

fluentd:
  defaults:
    host: localhost
    port: 24224
    tag: spring.fluentd
  dw:
    host: localhost
    port: 24224
    tag: was.dw

# LOGBACK CONFIG
logback:
  config.charset: UTF-8
  console.pattern: "%clr(%5p) %clr(%d{yy-MM-dd HH:mm:ss}){magenta}[%thread] [%clr(%logger{0}){cyan}:%line] - %msg%n"
  file:
    path: log/local/cheat/
    name: file.log
    pattern: "%clr(%5p) %clr(%d{yy-MM-dd HH:mm:ss}){magenta}[%thread] [%clr(%logger{35}){cyan}:%line] - %msg%n"
    rolling_policy:
      file_name_pattern: "file.%d{yyyy-MM-dd}-%i.gz"
      max_file_size: 100MB
      max_history: 30
  access:
    path: log/local/cheat/
    name: access.log
    pattern: "%msg%n"
    rolling_policy:
      file_name_pattern: "access.%d{yyyy-MM-dd}-%i.gz"
      max_file_size: 100MB
      max_history: 30